name: kltools
channels:
  - conda-forge
dependencies:
  - astropy
  - corner
  - emcee
  - fitsio
  - galsim
  - ipdb
  - jupyter
  - jupyterlab
  - mpi4py
  - numba
  - numpy==1.26.4
  - openmpi
  - pudb
  - schwimmbad
  - scipy
  - snakeviz
  - zeus-mcmc
  - pip:
    - pocomc
    - ultranest
