name: kltools
##prefix: /groups/timeifler/jiachuanxu/python_envs/envs/cocoa_ext
##prefix: /groups/timeifler/jiachuanxu/conda_envs/kltools
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy
  - numpy=1.22
  - jupyter
  - pudb
  - galsim
  - numba
  - zeus-mcmc
  - jupyterlab
  - corner
  - snakeviz
  - emcee
  - schwimmbad
  - openmpi
  - mpi4py
  - fitsio
  - ipdb
  - scipy
  - h5py
  - pip
  - pip:
    - getdist
